# Generated by Django 3.2.11 on 2024-04-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='media/excel/')),
                ('laz_file', models.FileField(upload_to='media/laz/')),
                ('obj_file', models.FileField(upload_to='media/obj/')),
                ('kml_file', models.FileField(upload_to='media/kml/')),
            ],
        ),
    ]
